spring:
  profiles:
    active: dev

---
spring:
  datasource:
    url: jdbc:mysql:///libsystem
    username: root
    password: xc19961016
    driver-class-name: com.mysql.jdbc.Driver
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080

---
spring:
  datasource:
    url: jdbc:mysql:///libsystem
    username: root
    password: Mysql123
    driver-class-name: com.mysql.jdbc.Driver
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080